version: '3.8'

services:
  discord-bot:
    image: ghcr.io/reavnail/leetcode-discord-bot:latest
    build:
      context: .
      dockerfile: packages/discord-bot/Dockerfile
    container_name: discord-bot
    environment:
      - TOKEN=${TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 11 * * *}
      - ADMIN_PASSCODE=${ADMIN_PASSCODE:-4444}
      - ENABLE_AUTO_DEPLOY=${ENABLE_AUTO_DEPLOY:-false}
    restart: unless-stopped
