# Create a workflow that runs on pull request events to check if the code compiles
# and passes eslint checks.

name: ESLint Review

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    eslint-fix:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.ref }}
                  
            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x

            - name: Install Lerna
              run: npm install -g lerna

            - name: Install Dependencies
              run: npm ci
            
            - name: Bootstrap Packages
              run: lerna bootstrap

            - name: Run ESLint
              run: lerna run lint:fix --verbose
              env:
                  CI: true

            - name: Check for Potential Fixes
              id: changes
              run: |
                git diff --quiet && echo "No changes" || echo "::set-output name=changes_detected::true"
                
            - name: Commit and Push New Fixes
              if: steps.changes.outputs.changes_detected
              run: |
                git config --global user.name "GitHub Actions Bot"
                git config --global user.email "github-actions-bot@example.com"
                git add .
                git commit -m "ESLint autofix [skip ci]"
                git push