# Create a workflow that runs on pull request events to check if the code compiles
# and passes eslint checks.

name: ESLint Review

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    eslint-fix:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.ref }}

            - name: Clean Cache
              run: npm install -g npm

            - name: Install Lerna
              run: npm install -g lerna

            - name: Install Dependencies
              run: npm ci
            
            - name: Bootstrap Packages
              run: lerna bootstrap

            - name: Run ESLint
              run: lerna run lint:fix --verbose
              env:
                  CI: true
