# Create a workflow that runs on pull request events to check if the code compiles
# and passes eslint checks.

name: ESLint Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install -g lerna
      - run: lerna bootstrap
      - run: lerna run lint:fix
        env:
          CI: true