name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Replace the <your-deploy-key> placeholder with the actual key name
          ssh-key: ${{ secrets.SSH-Perms }}

      - name: Install Node.js and PM2
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
        run: |
          npm install pm2 -g

      - name: Install dependencies
        run: npm install

      - name: Deploy application
        run: pm2 deploy ecosystem.config.js production restart
