name: Deploy LeetCode-Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install PM2
        run: npm install -g pm2

      - name: Install dependencies
        run: npm install
        
      - name: libcrypto
        run: sudo apt-get update && sudo apt-get install libssl-dev

      - name: Deploy
        env:
          SSH_KEY: ${{ secrets.SSH_PERMS }}
        run: |
          SSH_KEY_FILE="/path/to/ssh/key"
          eval $(ssh-agent -s)
          echo "$SSH_KEY" | tr -d '\r' | ssh-add "$SSH_KEY_FILE"
          ssh -o "StrictHostKeyChecking=no" root@10.0.0.45 "pm2 deploy ecosystem.config.js production setup && pm2 deploy ecosystem.config.js production --force"

      - name: Restart pm2
        run: pm2 startOrRestart LeetCode-Bot
